services:
    book_manager:
        class: AppBundle\Services\BookManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    app.form_book :
        class: AppBundle\Form\BookType
        tags:
            - { name: form.type, alias: appbundle_book}
    app.form.type.datepicker:
        class: AppBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: datepicker }
    app.book :
        class : AppBundle\Form\BookRestType
        tags:
            - { name: form.type, alias: book}